### ISSUE TITLE
Redis >= 4 

### ISSUE THREAD

**Issue by MMartyn** [basecamp/easymon#24]
We are experiencing issues addressed with the following commit:
https://github.com/basecamp/easymon/commit/9472135b012972f664439d737874e41f6a0cc48b#diff-5892261b17dbd431a67ac4302cb920ca

Wondering if you would be able to release a new version to ruby gems when you have a moment.

Thanks.

**Comment by anoldguy** [comment]
So sorry about this taking so long!

I've pushed v1.4!
