### ISSUE TITLE
Please release gem update

### ISSUE THREAD

**Issue by zjeraar** [basecamp/easymon#38]
Can we release this version as 1.6.3 on rubygems?

In 1.6.2 this `Easymon::Repository.add("application-database", Easymon::ActiveRecordCheck.new(ActiveRecord::Base))` no longer works with Rails 7.2 and up and the fix is in the master.

I've just spend an hour debugging why my database did not connect in production, only to find that this wasn't the case, but Easymon thought it was.

**Comment by pagbrl** [comment]
Version 1.6.3 has been released to rubygems.
